# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  place_id: 'C9CA7958-43F0-11EB-9CFA-7273B03FF381',
  service_id: '1263'
}

# override variables
variables:
  trmnl: {
    plugin_settings: {
      instance_name: 'Nashville Waste Services',
    }
  }
